server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
spring:
  application:
    name: gateway
  config:
      uri: http://localhost:8099
      username: root
      password: s3cr3t
  cloud:
    gateway:
      default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
       add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
             - "http://localhost:4200/"
            allowCredentials: true
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/**