server:
  port: 8084
  error:
    include-message: always
    include-binding-errors: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
spring:
  application:
    name: gateway
  config:
      uri: http://localhost:8099
      username: root
      password: s3cr3t
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/gateway/**