
#Application Configuration
server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: client-service
  cloud:
    config:
      uri: http://localhost:8099
      username: root
      password: s3cr3t
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:postgresql://localhost:5432/nico_bd
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin
  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
Feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"