server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  application:
    name: core-tecjoin-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: gateway
          uri: lb://client-service
          predicates:
            - Path=/gateway/**