server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
spring:
  application:
    name: gateway
  config:
      uri: http://localhost:8099
      username: root
      password: s3cr3t
zuul:
  routes:
    foos:
      path: /**
      url: http://localhost:8082